# SPDX-License-Identifier: Apache-2.0
"""Calibration factors from done-task actuals.

`calibrate` still prints a diagnostic report (actual / PERT expected).
`calibrate --apply` writes `calibration.yaml`. That file stores a shrunk,
clamped ratio of actual hours to likely hours for each (assignee, task_type)
pair, plus fallbacks.

`estimate` previews raw PERT expected times the factor.
`apply-calibration` writes `estimate_hours.calibrated` and leaves
optimistic, likely, and pessimistic alone. The factor always scales the
raw PERT expected, so running it twice does not compound.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from decimal import Decimal, ROUND_HALF_UP
from pathlib import Path

from planner.model import Plan, Task
from planner.planedit import append_log, log_entry, set_calibrated, set_version
from planner.util import RATIO_QUANTUM, fmt_hours, parse_datetime
from planner.yamlio import dump_yaml, load_yaml

PRIOR_STRENGTH = 3
CLAMP_MIN = Decimal("0.5")
CLAMP_MAX = Decimal("2")
METHOD = "actual_over_likely_shrunk"
LOOKUP = (
    "plan pair, then plan task_type, then plan assignee, then plan factor, "
    "then pair, then task_type, then assignee, then overall, then template_kind, else 1"
)

HEADER = (
    "# Generated by `python -m planner calibrate --apply`. Do not edit by hand.\n"
    "# factor = clamp(1 + (n / (n + prior_strength)) * (pooled actual/likely - 1)).\n"
    "# Samples are done tasks only. The schedule multiplies raw PERT expected by factor.\n"
    "# Optimistic, likely, and pessimistic are never rewritten by this file.\n"
    "# by_kind groups those samples by plan.template_kind. Plan overrides are not stored here.\n"
)


def q_ratio(value: Decimal) -> Decimal:
    return value.quantize(RATIO_QUANTUM, rounding=ROUND_HALF_UP)


def shrink(raw: Decimal, n: int, prior: int, low: Decimal, high: Decimal) -> Decimal:
    """Pull `raw` toward 1.0, then clamp. n=0 stays at 1."""
    if n <= 0:
        return Decimal(1)
    weight = Decimal(n) / Decimal(n + prior)
    factor = Decimal(1) + weight * (raw - Decimal(1))
    if factor < low:
        factor = low
    if factor > high:
        factor = high
    return q_ratio(factor)


@dataclass
class Factor:
    n: int
    raw_ratio: Decimal | None
    factor: Decimal


@dataclass
class Calibration:
    prior_strength: int
    clamp_min: Decimal
    clamp_max: Decimal
    samples: int
    skipped_zero_likely: int
    source_plans: list[str]
    as_of: str | None
    overall: Factor
    by_pair: dict[tuple[str, str], Factor]
    by_task_type: dict[str, Factor]
    by_assignee: dict[str, Factor]
    by_kind: dict[str, Factor]


@dataclass
class _Sample:
    assignee: str
    task_type: str
    likely: Decimal
    actual: Decimal
    end: datetime | None
    kind: str | None = None


def _empty_factor() -> Factor:
    return Factor(n=0, raw_ratio=None, factor=Decimal(1))


def identity_calibration(source_plans: list[str] | None = None) -> Calibration:
    return Calibration(
        prior_strength=PRIOR_STRENGTH,
        clamp_min=CLAMP_MIN,
        clamp_max=CLAMP_MAX,
        samples=0,
        skipped_zero_likely=0,
        source_plans=list(source_plans or []),
        as_of=None,
        overall=_empty_factor(),
        by_pair={},
        by_task_type={},
        by_assignee={},
        by_kind={},
    )


def _collect(plans: list[Plan]) -> tuple[list[_Sample], int]:
    samples: list[_Sample] = []
    skipped = 0
    for plan in plans:
        for task in plan.tasks:
            if task.status != "done" or task.actuals.hours is None:
                continue
            if task.estimate_hours.likely == 0:
                skipped += 1
                continue
            end = None
            if task.actuals.end:
                try:
                    end = parse_datetime(task.actuals.end, f"{task.id}.actuals.end")
                except ValueError:
                    end = None
            samples.append(
                _Sample(
                    assignee=task.assignee,
                    task_type=task.task_type,
                    likely=task.estimate_hours.likely,
                    actual=task.actuals.hours,
                    end=end,
                    kind=plan.template_kind,
                )
            )
    return samples, skipped


def _factor_for(samples: list[_Sample], prior: int, low: Decimal, high: Decimal) -> Factor:
    if not samples:
        return _empty_factor()
    actual = sum((sample.actual for sample in samples), Decimal(0))
    likely = sum((sample.likely for sample in samples), Decimal(0))
    raw = actual / likely
    return Factor(n=len(samples), raw_ratio=q_ratio(raw), factor=shrink(raw, len(samples), prior, low, high))


def build_calibration(plans: list[Plan]) -> Calibration:
    samples, skipped = _collect(plans)
    source = sorted({plan.plan_id for plan in plans})
    ends = [sample.end for sample in samples if sample.end is not None]
    as_of = max(ends).isoformat() if ends else None
    pairs: dict[tuple[str, str], list[_Sample]] = {}
    by_type: dict[str, list[_Sample]] = {}
    by_assignee: dict[str, list[_Sample]] = {}
    by_kind: dict[str, list[_Sample]] = {}
    for sample in samples:
        pairs.setdefault((sample.assignee, sample.task_type), []).append(sample)
        by_type.setdefault(sample.task_type, []).append(sample)
        by_assignee.setdefault(sample.assignee, []).append(sample)
        if sample.kind:
            by_kind.setdefault(sample.kind, []).append(sample)
    return Calibration(
        prior_strength=PRIOR_STRENGTH,
        clamp_min=CLAMP_MIN,
        clamp_max=CLAMP_MAX,
        samples=len(samples),
        skipped_zero_likely=skipped,
        source_plans=source,
        as_of=as_of,
        overall=_factor_for(samples, PRIOR_STRENGTH, CLAMP_MIN, CLAMP_MAX),
        by_pair={
            key: _factor_for(pairs[key], PRIOR_STRENGTH, CLAMP_MIN, CLAMP_MAX)
            for key in sorted(pairs)
        },
        by_task_type={
            key: _factor_for(by_type[key], PRIOR_STRENGTH, CLAMP_MIN, CLAMP_MAX)
            for key in sorted(by_type)
        },
        by_assignee={
            key: _factor_for(by_assignee[key], PRIOR_STRENGTH, CLAMP_MIN, CLAMP_MAX)
            for key in sorted(by_assignee)
        },
        by_kind={
            key: _factor_for(by_kind[key], PRIOR_STRENGTH, CLAMP_MIN, CLAMP_MAX)
            for key in sorted(by_kind)
        },
    )


def _factor_doc(factor: Factor) -> dict:
    return {
        "n": factor.n,
        "raw_ratio": factor.raw_ratio,
        "factor": factor.factor,
    }


def calibration_document(cal: Calibration) -> dict:
    pairs = []
    for assignee, task_type in sorted(cal.by_pair):
        body = _factor_doc(cal.by_pair[(assignee, task_type)])
        pairs.append({"assignee": assignee, "task_type": task_type, **body})
    types = []
    for name in sorted(cal.by_task_type):
        types.append({"task_type": name, **_factor_doc(cal.by_task_type[name])})
    assignees = []
    for name in sorted(cal.by_assignee):
        assignees.append({"assignee": name, **_factor_doc(cal.by_assignee[name])})
    kinds = []
    for name in sorted(cal.by_kind):
        kinds.append({"kind": name, **_factor_doc(cal.by_kind[name])})
    return {
        "schema_version": 1,
        "method": METHOD,
        "lookup": LOOKUP,
        "prior_strength": cal.prior_strength,
        "clamp_min": cal.clamp_min,
        "clamp_max": cal.clamp_max,
        "samples": cal.samples,
        "skipped_zero_likely": cal.skipped_zero_likely,
        "as_of": cal.as_of,
        "source_plans": list(cal.source_plans),
        "overall": _factor_doc(cal.overall),
        "by_pair": pairs,
        "by_task_type": types,
        "by_assignee": assignees,
        "by_kind": kinds,
    }


def render_calibration_yaml(cal: Calibration) -> str:
    return HEADER + dump_yaml(calibration_document(cal))


def _as_factor(raw, where: str) -> Factor:
    if not isinstance(raw, dict):
        raise ValueError(f"{where} must be a mapping")
    n = raw.get("n")
    if isinstance(n, bool) or not isinstance(n, int) or n < 0:
        raise ValueError(f"{where}.n must be an integer >= 0")
    factor = raw.get("factor")
    if isinstance(factor, bool) or not isinstance(factor, (int, float, Decimal, str)):
        raise ValueError(f"{where}.factor must be a number")
    factor_n = Decimal(str(factor))
    ratio = raw.get("raw_ratio")
    ratio_n = None if ratio is None else Decimal(str(ratio))
    return Factor(n=n, raw_ratio=ratio_n, factor=factor_n)


def load_calibration(path: Path) -> Calibration:
    data = load_yaml(path)
    if not isinstance(data, dict):
        raise ValueError(f"{path} must be a mapping")
    if data.get("schema_version") != 1:
        raise ValueError(f"{path} schema_version must be 1")
    try:
        prior = int(data.get("prior_strength", PRIOR_STRENGTH))
        low = Decimal(str(data.get("clamp_min", CLAMP_MIN)))
        high = Decimal(str(data.get("clamp_max", CLAMP_MAX)))
    except Exception as exc:
        raise ValueError(f"{path} has an unreadable clamp or prior") from exc
    source = data.get("source_plans") or []
    if not isinstance(source, list):
        raise ValueError("source_plans must be a list")
    by_pair: dict[tuple[str, str], Factor] = {}
    for index, row in enumerate(data.get("by_pair") or []):
        if not isinstance(row, dict):
            raise ValueError(f"by_pair[{index}] must be a mapping")
        key = (str(row.get("assignee", "")), str(row.get("task_type", "")))
        by_pair[key] = _as_factor(row, f"by_pair[{index}]")
    by_type = {}
    for index, row in enumerate(data.get("by_task_type") or []):
        if not isinstance(row, dict):
            raise ValueError(f"by_task_type[{index}] must be a mapping")
        by_type[str(row.get("task_type", ""))] = _as_factor(row, f"by_task_type[{index}]")
    by_assignee = {}
    for index, row in enumerate(data.get("by_assignee") or []):
        if not isinstance(row, dict):
            raise ValueError(f"by_assignee[{index}] must be a mapping")
        by_assignee[str(row.get("assignee", ""))] = _as_factor(row, f"by_assignee[{index}]")
    by_kind = {}
    for index, row in enumerate(data.get("by_kind") or []):
        if not isinstance(row, dict):
            raise ValueError(f"by_kind[{index}] must be a mapping")
        by_kind[str(row.get("kind", ""))] = _as_factor(row, f"by_kind[{index}]")
    as_of = data.get("as_of")
    if as_of is not None:
        as_of = str(as_of)
    return Calibration(
        prior_strength=prior,
        clamp_min=low,
        clamp_max=high,
        samples=int(data.get("samples") or 0),
        skipped_zero_likely=int(data.get("skipped_zero_likely") or 0),
        source_plans=[str(item) for item in source],
        as_of=as_of,
        overall=_as_factor(data.get("overall") or {"n": 0, "raw_ratio": None, "factor": 1}, "overall"),
        by_pair=by_pair,
        by_task_type=by_type,
        by_assignee=by_assignee,
        by_kind=by_kind,
    )


def calibration_for(plan: Plan) -> Calibration:
    """Load the repo calibration file next to plans/, or an identity file."""
    if plan.directory is None:
        return identity_calibration()
    path = plan.directory.parent.parent / "calibration.yaml"
    if not path.is_file():
        return identity_calibration()
    return load_calibration(path)


def lookup(cal: Calibration, assignee: str, task_type: str) -> tuple[Decimal, int, str]:
    pair = cal.by_pair.get((assignee, task_type))
    if pair is not None and pair.n > 0:
        return pair.factor, pair.n, "pair"
    kind = cal.by_task_type.get(task_type)
    if kind is not None and kind.n > 0:
        return kind.factor, kind.n, "task_type"
    who = cal.by_assignee.get(assignee)
    if who is not None and who.n > 0:
        return who.factor, who.n, "assignee"
    if cal.overall.n > 0:
        return cal.overall.factor, cal.overall.n, "overall"
    return Decimal(1), 0, "none"


def resolve_factor(cal: Calibration, task: Task, plan: Plan | None = None) -> tuple[Decimal, int, str]:
    """Plan override, then the shared file, then template_kind, else 1.

    A plan blanket factor is more specific than the shared file. It applies
    to every task in that plan that has no pair, type, or assignee override.
    """
    if plan is not None and plan.calibration_override is not None:
        override = plan.calibration_override
        pair = override.by_pair.get((task.assignee, task.task_type))
        if pair is not None:
            return pair, 0, "plan_pair"
        typed = override.by_task_type.get(task.task_type)
        if typed is not None:
            return typed, 0, "plan_task_type"
        who = override.by_assignee.get(task.assignee)
        if who is not None:
            return who, 0, "plan_assignee"
        if override.factor is not None:
            return override.factor, 0, "plan_factor"
    factor, count, basis = lookup(cal, task.assignee, task.task_type)
    if basis != "none":
        return factor, count, basis
    if plan is not None and plan.template_kind:
        kind = cal.by_kind.get(plan.template_kind)
        if kind is not None and kind.n > 0:
            return kind.factor, kind.n, "template_kind"
    return Decimal(1), 0, "none"


def preview_hours(task: Task, cal: Calibration, plan: Plan | None = None) -> tuple[Decimal, Decimal, int, str]:
    """Return (raw PERT expected, calibrated hours, n, basis)."""
    factor, count, basis = resolve_factor(cal, task, plan)
    raw = task.estimate_hours.expected
    adjusted = (raw * factor).quantize(Decimal("0.0001"), rounding=ROUND_HALF_UP)
    return raw, adjusted, count, basis


def apply_calibration(plan: Plan, cal: Calibration, *, at: str) -> tuple[bool, str]:
    """Write estimate_hours.calibrated from raw PERT expected times the factor.

    Returns (changed, message). Optimistic, likely, and pessimistic are not edited.
    Version bumps only when a calibrated value changes.
    """
    if plan.path is None or plan.directory is None:
        raise ValueError("plan has no directory")
    text = plan.path.read_text(encoding="utf-8")
    changed = 0
    for task in plan.tasks:
        _raw, adjusted, _count, _basis = preview_hours(task, cal, plan)
        if task.estimate_hours.calibrated == adjusted:
            continue
        text = set_calibrated(text, task.id, adjusted)
        changed += 1
    if changed == 0:
        return False, f"unchanged: {plan.plan_id} calibrated hours already match calibration.yaml"
    new_version = plan.version + 1
    text = set_version(text, new_version)
    plan.path.write_text(text, encoding="utf-8")
    frozen = [task.id for task in plan.tasks if task.status in {"in_progress", "in_review"}]
    append_log(
        plan.directory / "log.md",
        log_entry(
            version=new_version,
            at=at,
            kind="apply-calibration",
            reason="Write estimate_hours.calibrated from calibration.yaml.",
            change=(
                f"Set calibrated hours on {changed} tasks by multiplying raw PERT expected "
                "by the stored factor. Optimistic, likely, and pessimistic were not changed."
            ),
            frozen=frozen,
        ),
    )
    return True, f"wrote calibrated hours on {changed} tasks in {plan.plan_id} at version {new_version}"


def render_estimate(plan: Plan, cal: Calibration, *, source: str) -> str:
    lines = [
        f"plan: {plan.plan_id}",
        f"calibration: {source}",
        f"lookup: {LOOKUP}",
        "tasks:",
    ]
    for task in plan.tasks:
        raw, adjusted, count, basis = preview_hours(task, cal, plan)
        factor, _count, _basis = resolve_factor(cal, task, plan)
        stored = task.estimate_hours.calibrated
        if stored is None:
            stored_text = "(none)"
        else:
            stored_text = fmt_hours(stored) + "h"
        stale = ""
        if stored is not None and stored != adjusted:
            stale = " stale"
        lines.append(
            f"  {task.id} | {task.assignee} | {task.task_type} | "
            f"raw {fmt_hours(raw)}h | factor {fmt_hours(factor)} | "
            f"n={count} | basis {basis} | preview {fmt_hours(adjusted)}h | "
            f"stored {stored_text}{stale}"
        )
    if not plan.tasks:
        lines.append("  (none)")
    lines.append("raw optimistic, likely, and pessimistic are not modified by estimate.")
    return "\n".join(lines)
