# SPDX-License-Identifier: Apache-2.0
"""Static dashboard and a meeting-prep digest.

`dashboard` and `digest` write files. `serve` exposes those files on localhost
for Tailscale. `digest --post` is the only path that sends the text to Slack,
and only when SLACK_DIGEST_WEBHOOK is set.
"""

from __future__ import annotations

import re
from datetime import timedelta
from decimal import Decimal
from pathlib import Path

from planner.forecast import format_forecast, project
from planner.leveling import is_open, level_plans
from planner.model import Plan, Roster
from planner.reports import ScheduleResult, is_awaiting_human, is_dispatchable
from planner.util import add_hours, fmt_hours, parse_datetime

_SECTION = re.compile(r"(?=^## )", re.M)


def last_log_section(text: str) -> str:
    parts = [part.strip() for part in _SECTION.split(text) if part.strip().startswith("##")]
    if not parts:
        return "(no log)"
    return parts[-1]


def _esc(text: str) -> str:
    return (
        text.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


def _ready(plan: Plan, result: ScheduleResult) -> list:
    known = {task.id: task for task in plan.tasks}
    tasks = [task for task in plan.tasks if is_dispatchable(task, known)]
    tasks.sort(key=lambda task: task.id)
    return tasks


def _gates(plan: Plan) -> list:
    known = {task.id: task for task in plan.tasks}
    tasks = [task for task in plan.tasks if is_awaiting_human(task, known)]
    tasks.sort(key=lambda task: task.id)
    return tasks


def _next_window(document: dict, at) -> list[dict]:
    if not document.get("origin"):
        return []
    origin = parse_datetime(document["origin"], "origin")
    end = at + timedelta(hours=24)
    rows = []
    for row in document.get("tasks") or []:
        start = add_hours(origin, row["start"])
        finish = add_hours(origin, row["finish"])
        if row["duration_hours"] == 0:
            overlaps = at <= start < end
        else:
            overlaps = start < end and finish > at
        if overlaps:
            rows.append(
                {
                    **row,
                    "start_at": start.isoformat(),
                    "finish_at": finish.isoformat(),
                }
            )
    return rows


def render_digest(plans: list[Plan], roster: Roster, results: dict[str, ScheduleResult], at) -> str:
    open_plans = [plan for plan in plans if is_open(plan)]
    document = level_plans(open_plans, roster) if open_plans else {"origin": None, "tasks": [], "makespan_hours": Decimal(0)}
    window_end = (at + timedelta(hours=24)).isoformat()
    lines = [
        "# Digest",
        "",
        "Generated by `python -m planner digest`. Do not edit by hand.",
        "Meeting prep: what changed, decisions needed, risks, next 24h.",
        "Dry run writes this file and dashboard/slack-payload.json.",
        "Post with `digest --post` when SLACK_DIGEST_WEBHOOK is set.",
        "",
        f"- As of: {at.isoformat()}",
        f"- Next 24h through: {window_end}",
        "",
        "## What changed",
        "",
    ]
    if not plans:
        lines.append("(no live plans)")
        lines.append("")
    for plan in plans:
        lines.append(f"### {plan.plan_id}")
        lines.append("")
        log = ""
        if plan.directory is not None and (plan.directory / "log.md").is_file():
            log = (plan.directory / "log.md").read_text(encoding="utf-8")
        lines.append(last_log_section(log) if log else "(no log)")
        lines.append("")
    lines.extend(["## Decisions needed", ""])
    decisions = []
    for plan in plans:
        for task in _gates(plan):
            decisions.append(f"- {plan.plan_id} {task.id}: {task.title} ({task.assignee})")
    lines.extend(decisions or ["- (none)"])
    lines.extend(["", "## Risks", ""])
    risks = []
    for plan in plans:
        result = results.get(plan.plan_id)
        forecast = project(plan, result, roster)
        if forecast.warnings:
            risks.append(
                f"- {plan.plan_id}: forecast warning on {', '.join(forecast.warnings)}"
                + (" (over budget)" if forecast.hold else " (before breach)")
            )
        blocked = [task.id for task in plan.tasks if task.status == "blocked"]
        failed = [task.id for task in plan.tasks if task.status == "failed"]
        if blocked:
            risks.append(f"- {plan.plan_id} blocked: {', '.join(blocked)}")
        if failed:
            risks.append(f"- {plan.plan_id} failed: {', '.join(failed)}")
    lines.extend(risks or ["- (none)"])
    lines.extend(["", "## Next 24h", ""])
    upcoming = _next_window(document, at)
    if not upcoming:
        lines.append("- (none)")
    else:
        for row in upcoming:
            lines.append(
                f"- {row['plan_id']} {row['task_id']} {row['assignee']} "
                f"{row['start_at']} to {row['finish_at']}"
            )
    lines.append("")
    return "\n".join(lines)


def render_dashboard_md(plans: list[Plan], roster: Roster, results: dict[str, ScheduleResult], at) -> str:
    open_plans = [plan for plan in plans if is_open(plan)]
    document = level_plans(open_plans, roster) if open_plans else {
        "origin": None,
        "tasks": [],
        "makespan_hours": Decimal(0),
        "overallocated": [],
        "ordering": "priority, then deadline, then least slack",
    }
    lines = [
        "# Dashboard",
        "",
        "Generated by `python -m planner dashboard`. Do not edit by hand.",
        "Read-only. A later bot UI can serve this file. Nothing here calls the network.",
        "",
        f"- As of: {at.isoformat()}",
        f"- Live plans: {len(plans)}",
        f"- Open plans in the shared schedule: {len(open_plans)}",
        f"- Shared ordering: {document.get('ordering', 'priority, then deadline, then least slack')}",
        f"- Shared makespan hours: {fmt_hours(document.get('makespan_hours') or Decimal(0))}",
        f"- Over-allocated assignees: {', '.join(document.get('overallocated') or []) or '(none)'}",
        "",
        "## Portfolio",
        "",
    ]
    if not plans:
        lines.append("No live plans.")
        lines.append("")
    for plan in plans:
        result = results.get(plan.plan_id)
        forecast = project(plan, result, roster)
        done = sum(1 for task in plan.tasks if task.status == "done")
        active = sum(1 for task in plan.tasks if task.status != "cancelled")
        lines.append(f"### {plan.plan_id}")
        lines.append("")
        lines.append(f"- Progress: {done}/{active}")
        if result is not None:
            lines.append(f"- Makespan hours: {fmt_hours(result.makespan)}")
            lines.append(f"- Critical path: {' -> '.join(result.critical_path) or '(none)'}")
        lines.append(f"- Priority: {plan.priority}")
        for row in format_forecast(forecast):
            lines.append("- " + row.strip())
        lines.append(f"- Forecast hold: {'yes' if forecast.hold else 'no'}")
        subs = [task for task in plan.tasks if task.subplan]
        if subs and result is not None:
            for task in subs:
                status = result.rolled_status.get(task.id, task.status)
                lines.append(f"- Subplan {task.id}: {task.subplan} ({status})")
        else:
            lines.append("- Subplans: (none)")
        lines.append("")
    lines.extend(
        [
            "## Gantt snapshot",
            "",
            "Times are hours after the shared origin. This is the leveled schedule.",
            "",
            "| Plan | Task | Assignee | Start | Finish |",
            "| --- | --- | --- | --- | --- |",
        ]
    )
    for row in document.get("tasks") or []:
        lines.append(
            f"| {row['plan_id']} | {row['task_id']} | {row['assignee']} | "
            f"{fmt_hours(row['start'])} | {fmt_hours(row['finish'])} |"
        )
    if not document.get("tasks"):
        lines.append("| (none) | | | | |")
    lines.extend(["", "## Ready queue", ""])
    ready_lines = []
    for plan in plans:
        result = results.get(plan.plan_id)
        if result is None:
            continue
        for task in _ready(plan, result):
            ready_lines.append(f"- {plan.plan_id} {task.id} | {task.assignee} | briefs/{task.id}.md")
    lines.extend(ready_lines or ["- (none)"])
    lines.extend(["", "## Gates waiting", ""])
    gate_lines = []
    for plan in plans:
        for task in _gates(plan):
            gate_lines.append(f"- {plan.plan_id} {task.id} | {task.assignee} | {task.title}")
    lines.extend(gate_lines or ["- (none)"])
    lines.extend(["", "## Burn versus forecast", ""])
    for plan in plans:
        result = results.get(plan.plan_id)
        forecast = project(plan, result, roster)
        lines.append(f"### {plan.plan_id}")
        lines.append("")
        lines.append(f"- Actual hours: {fmt_hours(forecast.actual_hours)}")
        lines.append(f"- Remaining hours: {fmt_hours(forecast.remaining_hours)}")
        for row in format_forecast(forecast):
            lines.append("- " + row.strip())
        lines.append(f"- Forecast hold: {'yes' if forecast.hold else 'no'}")
        lines.append("")
    return "\n".join(lines)


def render_dashboard_html(markdown: str, at) -> str:
    """Self-contained HTML. No scripts and no remote assets."""
    rows = []
    in_gantt = False
    for line in markdown.splitlines():
        if line.startswith("## Gantt snapshot"):
            in_gantt = True
            continue
        if in_gantt and line.startswith("## "):
            in_gantt = False
        if in_gantt and line.startswith("| ") and not line.startswith("| ---") and "Plan |" not in line:
            cells = [cell.strip() for cell in line.strip("|").split("|")]
            if len(cells) >= 5 and cells[0] != "(none)":
                rows.append(cells)
    makespan = Decimal(0)
    parsed = []
    for cells in rows:
        start = Decimal(cells[3])
        finish = Decimal(cells[4])
        if finish > makespan:
            makespan = finish
        parsed.append((cells[0], cells[1], cells[2], start, finish))
    bars = []
    for plan_id, task_id, assignee, start, finish in parsed:
        if makespan <= 0:
            left = Decimal(0)
            width = Decimal(100)
        else:
            left = (start / makespan) * Decimal(100)
            width = ((finish - start) / makespan) * Decimal(100)
            if width <= 0:
                width = Decimal("0.4")
        bars.append(
            "<div class=\"row\">"
            f"<div class=\"label\">{_esc(plan_id)} {_esc(task_id)} {_esc(assignee)}</div>"
            "<div class=\"track\"><div class=\"bar\" style=\""
            f"margin-left:{left:.2f}%;width:{width:.2f}%\"></div></div>"
            "</div>"
        )
    body = []
    table_open = False
    for line in markdown.splitlines():
        if line.startswith("| ---"):
            continue
        is_row = line.startswith("| ")
        if is_row:
            if not table_open:
                body.append("<table>")
                table_open = True
            cells = [cell.strip() for cell in line.strip("|").split("|")]
            tag = "th" if cells and cells[0] in {"Plan", "ID"} else "td"
            inner = "".join(f"<{tag}>{_esc(cell)}</{tag}>" for cell in cells)
            body.append(f"<tr>{inner}</tr>")
            continue
        if table_open:
            body.append("</table>")
            table_open = False
        if line.startswith("# "):
            body.append(f"<h1>{_esc(line[2:])}</h1>")
        elif line.startswith("## "):
            body.append(f"<h2>{_esc(line[3:])}</h2>")
        elif line.startswith("### "):
            body.append(f"<h3>{_esc(line[4:])}</h3>")
        elif line.startswith("- "):
            body.append(f"<p class=\"item\">{_esc(line[2:])}</p>")
        elif line.strip():
            body.append(f"<p>{_esc(line)}</p>")
    if table_open:
        body.append("</table>")
    stamp = _esc(at.isoformat())
    bar_html = "\n".join(bars) or "<p>(none)</p>"
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Fleet dashboard {stamp}</title>
<style>
body {{ font: 16px/1.45 Georgia, "Iowan Old Style", serif; margin: 2rem auto; max-width: 52rem; color: #1c1915; background: #f7f3ea; }}
h1, h2, h3 {{ font-family: "Palatino Linotype", Palatino, serif; }}
table {{ border-collapse: collapse; width: 100%; margin: 0.5rem 0 1.5rem; }}
th, td {{ border-bottom: 1px solid #d9d0c1; text-align: left; padding: 0.3rem 0.4rem; font-family: ui-monospace, monospace; font-size: 0.85rem; }}
.item {{ margin: 0.15rem 0; }}
.row {{ display: flex; gap: 0.75rem; align-items: center; margin: 0.25rem 0; }}
.label {{ width: 18rem; font-family: ui-monospace, monospace; font-size: 0.8rem; }}
.track {{ flex: 1; background: #efe8da; height: 0.8rem; }}
.bar {{ background: #3f5c4b; height: 0.8rem; }}
footer {{ margin-top: 2rem; color: #5c564c; }}
</style>
</head>
<body>
{"".join(body)}
<h2>Bars</h2>
{bar_html}
<footer>Static file. No network. As of {stamp}.</footer>
</body>
</html>
"""


def write_dashboard(root: Path, plans, roster, results, at) -> tuple[Path, Path]:
    folder = root / "dashboard"
    folder.mkdir(parents=True, exist_ok=True)
    markdown = render_dashboard_md(plans, roster, results, at)
    html = render_dashboard_html(markdown, at)
    md_path = folder / "index.md"
    html_path = folder / "index.html"
    md_path.write_text(markdown, encoding="utf-8")
    html_path.write_text(html, encoding="utf-8")
    return md_path, html_path


def write_digest(root: Path, plans, roster, results, at) -> tuple[Path, str]:
    folder = root / "dashboard"
    folder.mkdir(parents=True, exist_ok=True)
    text = render_digest(plans, roster, results, at)
    path = folder / "digest.md"
    path.write_text(text, encoding="utf-8")
    return path, text
