# SPDX-License-Identifier: Apache-2.0
"""Render a Mermaid Gantt chart from a computed schedule.

Bars use resource-constrained start and finish. `crit` marks unconstrained
CPM slack of zero. The chart is a view: regenerate it, do not edit it.
"""

from __future__ import annotations

from datetime import datetime
from decimal import Decimal, ROUND_HALF_UP

from planner.model import Plan
from planner.schedule import ScheduleResult
from planner.util import add_hours, fmt_hours, parse_datetime
from planner.yamlio import dump_yaml

SCHEDULE_NOTE = (
    "Heuristic schedule. CPM slack assumes unlimited agents. "
    "start and finish respect per-bot capacity and max_parallel. "
    "RCPSP is NP-hard; this priority list is not guaranteed optimal."
)


def schedule_document(plan: Plan, result: ScheduleResult) -> dict:
    by_task = {task.id: task for task in plan.tasks}
    tasks = []
    for task_id in result.topo:
        timing = result.by_id[task_id]
        task = by_task[task_id]
        entry = {
            "id": timing.id,
            "assignee": timing.assignee,
            "expected_hours": timing.expected,
        }
        if task.subplan:
            entry["subplan"] = task.subplan
            entry["rolled_status"] = result.rolled_status.get(task.id, task.status)
        # Present only when the author has a calibrated figure, so origin
        # schedules of uncalibrated plans stay byte-stable.
        if task.estimate_hours.calibrated is not None:
            entry["raw_expected_hours"] = task.estimate_hours.expected
            entry["calibrated_hours"] = task.estimate_hours.calibrated
        entry.update(
            {
                "std_dev_hours": timing.std_dev,
                "earliest_start": timing.earliest_start,
                "earliest_finish": timing.earliest_finish,
                "latest_start": timing.latest_start,
                "latest_finish": timing.latest_finish,
                "slack": timing.slack,
                "critical": timing.critical,
                "start": timing.start,
                "finish": timing.finish,
            }
        )
        tasks.append(entry)
    document = {
        "plan_id": plan.plan_id,
        "plan_version": plan.version,
        "scheduler": "priority-list-v1",
        "note": SCHEDULE_NOTE,
        "origin": plan.schedule_origin,
        "max_parallel": plan.max_parallel,
        "project": {
            "cpm_duration_hours": result.cpm_duration,
            "cpm_std_dev_hours": result.cpm_std_dev,
            "makespan_hours": result.makespan,
            "effort_hours": result.effort,
            "critical_path": list(result.critical_path),
            "critical_tasks": list(result.critical_tasks),
        },
        "tasks": tasks,
    }
    if result.mode == "from-now":
        document = {
            "plan_id": document["plan_id"],
            "plan_version": document["plan_version"],
            "scheduler": document["scheduler"],
            "mode": "from-now",
            "now_hours": result.now_hours if result.now_hours is not None else Decimal(0),
            "note": document["note"],
            "origin": document["origin"],
            "max_parallel": document["max_parallel"],
            "project": document["project"],
            "tasks": document["tasks"],
        }
    return document


def render_schedule_yaml(plan: Plan, result: ScheduleResult) -> str:
    body = dump_yaml(schedule_document(plan, result))
    if result.mode == "from-now":
        header = "# Generated by `python -m planner replan --now`. Do not edit by hand.\n"
    else:
        header = "# Generated by `python -m planner schedule`. Do not edit by hand.\n"
    return header + body


def _duration_token(hours: Decimal) -> str:
    minutes = (hours * Decimal(60)).quantize(Decimal("1"), rounding=ROUND_HALF_UP)
    if minutes == 0:
        return "0m"
    if minutes % 60 == 0:
        return f"{int(minutes // 60)}h"
    return f"{int(minutes)}m"


def _mermaid_id(task_id: str, used: set[str]) -> str:
    base = "".join(ch for ch in task_id.lower() if ch.isalnum()) or "task"
    candidate = base
    number = 2
    while candidate in used:
        candidate = f"{base}{number}"
        number += 1
    used.add(candidate)
    return candidate


def _label(text: str) -> str:
    cleaned = " ".join(text.replace(":", " ").replace("#", " ").split())
    return cleaned or "task"


def _clock(moment: datetime) -> str:
    return moment.strftime("%H:%M")


def _stamp(moment: datetime) -> str:
    return moment.strftime("%Y-%m-%d %H:%M")


def render_gantt(plan: Plan, result: ScheduleResult) -> str:
    origin = parse_datetime(plan.schedule_origin, "constraints.schedule_origin")
    use_dates = any(
        timing.finish >= 24 or timing.start >= 24 or timing.start < 0
        for timing in result.by_id.values()
    )
    title = _label(plan.title or plan.plan_id) + f" v{plan.version}"
    if result.mode == "from-now":
        generated = (
            "Generated from `plan.yaml` by `python -m planner replan --now`. Do not edit by hand."
        )
    else:
        generated = "Generated from `plan.yaml` by `python -m planner gantt`. Do not edit by hand."
    lines = [
        "# Gantt",
        "",
        generated,
        "",
        f"- Plan: {plan.plan_id} v{plan.version}",
        f"- Origin: {plan.schedule_origin}",
    ]
    if result.mode == "from-now":
        lines.append(
            f"- From now: {fmt_hours(result.now_hours or Decimal(0))}h after origin. "
            "In-progress and in-review tasks keep their start."
        )
    lines.extend(
        [
        f"- CPM duration: {fmt_hours(result.cpm_duration)}h "
        f"(std dev {fmt_hours(result.cpm_std_dev)}h along the critical path)",
        f"- Resource-constrained makespan: {fmt_hours(result.makespan)}h",
        f"- Critical path: {', '.join(result.critical_path) or '(none)'}",
        "- `crit` means unconstrained CPM slack is zero. Bar times are the resource-constrained schedule.",
        "",
        "| ID | Start | Finish | Slack | Assignee | Critical |",
        "| --- | --- | --- | --- | --- | --- |",
        ]
    )
    if result.rolled_status:
        note = "- Subplan rollup: " + "; ".join(
            f"{task_id} is {status}"
            for task_id, status in sorted(result.rolled_status.items())
        )
        for index, line in enumerate(lines):
            if line.startswith("| ID |"):
                lines.insert(index, note)
                break
    ordered = sorted(
        result.by_id.values(),
        key=lambda timing: (timing.start, timing.id),
    )
    for timing in ordered:
        lines.append(
            "| {id} | {start} | {finish} | {slack} | {assignee} | {critical} |".format(
                id=timing.id,
                start=fmt_hours(timing.start),
                finish=fmt_hours(timing.finish),
                slack=fmt_hours(timing.slack),
                assignee=timing.assignee,
                critical="yes" if timing.critical else "no",
            )
        )
    lines.extend(["", "```mermaid", "gantt"])
    lines.append(f"    title {title}")
    if use_dates:
        lines.append("    dateFormat YYYY-MM-DD HH:mm")
        lines.append("    axisFormat %m-%d %H:%M")
    else:
        lines.append("    dateFormat HH:mm")
        lines.append("    axisFormat %H:%M")

    sections: list[str] = []
    members: dict[str, list] = {}
    for task in plan.tasks:
        if task.id not in result.by_id:
            continue
        section = task.section or task.assignee
        if section not in members:
            sections.append(section)
            members[section] = []
        members[section].append(task)
    used_ids: set[str] = set()

    def in_section(task):
        return result.by_id[task.id]

    for section in sections:
        lines.append(f"    section {_label(section)}")
        group = sorted(members[section], key=lambda task: (in_section(task).start, task.id))
        for task in group:
            timing = result.by_id[task.id]
            start = add_hours(origin, timing.start)
            token = _duration_token(timing.expected)
            tags = []
            if timing.expected == 0:
                tags.append("milestone")
            if timing.critical:
                tags.append("crit")
            shown = result.rolled_status.get(task.id, task.status)
            if shown == "done":
                tags.append("done")
            elif shown in {"in_progress", "in_review"}:
                tags.append("active")
            tag_text = (", ".join(tags) + ", ") if tags else ""
            when = _stamp(start) if use_dates else _clock(start)
            label = _label(f"{task.id} {task.title} - {task.assignee}")
            lines.append(
                f"    {label} :{tag_text}{_mermaid_id(task.id, used_ids)}, {when}, {token}"
            )
    lines.extend(["```", ""])
    return "\n".join(lines)
