# SPDX-License-Identifier: Apache-2.0
"""Portfolio rollup across live plans.

portfolio.md and portfolio.yaml are generated views, like schedule.yaml.
They use the origin-based schedule (calibrated hours when that field is set).
A from-now replan does not change this rollup until the plan's estimates or
status change and someone runs portfolio again.
"""

from __future__ import annotations

from decimal import Decimal

from planner.forecast import project
from planner.model import STATUSES, Plan, Roster
from planner.reports import ScheduleResult, is_awaiting_human
from planner.util import (
    add_hours,
    fmt_hours,
    fmt_percent,
    fmt_ratio,
    hours_between,
    parse_datetime,
    plan_directory_label,
)
from planner.yamlio import dump_yaml

HEADER_MD = (
    "# Portfolio\n\n"
    "Generated by `python -m planner portfolio`. Do not edit by hand.\n\n"
    "Numbers use the origin-based schedule. `critical residual hours` is the "
    "sum of scheduling durations of unfinished critical-path tasks. That is "
    "remaining critical effort, not a promise that the calendar gap equals it "
    "when tasks overlap.\n"
)


def _variance(plan: Plan) -> dict:
    actual = Decimal(0)
    expected = Decimal(0)
    count = 0
    for task in plan.tasks:
        if task.actuals.hours is None:
            continue
        duration = task.estimate_hours.expected
        if duration == 0:
            continue
        actual += task.actuals.hours
        expected += duration
        count += 1
    if count == 0:
        return {
            "samples": 0,
            "actual_hours": None,
            "expected_hours": None,
            "pooled_ratio": None,
        }
    return {
        "samples": count,
        "actual_hours": actual,
        "expected_hours": expected,
        "pooled_ratio": actual / expected,
    }


def _estimate_error(plan: Plan, active: list) -> dict | None:
    if not active or any(task.status != "done" for task in active):
        return None
    raw = Decimal(0)
    calibrated = Decimal(0)
    actual = Decimal(0)
    have_calibrated = False
    for task in active:
        if task.actuals.hours is None or task.estimate_hours.expected == 0:
            continue
        raw += task.estimate_hours.expected
        actual += task.actuals.hours
        if task.estimate_hours.calibrated is not None:
            have_calibrated = True
            calibrated += task.estimate_hours.calibrated
        else:
            calibrated += task.estimate_hours.expected
    if raw == 0:
        return None
    body = {
        "actual_hours": actual,
        "raw_expected_hours": raw,
        "pooled_ratio_vs_raw": actual / raw,
    }
    if have_calibrated and calibrated != 0:
        body["calibrated_hours"] = calibrated
        body["pooled_ratio_vs_calibrated"] = actual / calibrated
    return body


def _residual(plan: Plan, result: ScheduleResult) -> tuple[list[str], Decimal]:
    known = {task.id: task for task in plan.tasks}
    ids: list[str] = []
    hours = Decimal(0)
    for task_id in result.critical_path:
        task = known.get(task_id)
        if task is None or task.status in {"done", "cancelled"}:
            continue
        ids.append(task_id)
        timing = result.by_id.get(task_id)
        if timing is not None:
            hours += timing.expected
    return ids, hours


def _id_list(tasks) -> list[str]:
    return [task.id for task in tasks]


def plan_entry(plan: Plan, result: ScheduleResult, roster: Roster | None = None) -> dict:
    known = {task.id: task for task in plan.tasks}
    active = [task for task in plan.tasks if task.status != "cancelled"]
    done = [task for task in active if task.status == "done"]
    blocked = [task for task in plan.tasks if task.status == "blocked"]
    failed = [task for task in plan.tasks if task.status == "failed"]
    waiting = [task for task in plan.tasks if is_awaiting_human(task, known)]
    counts = {status: 0 for status in STATUSES}
    for task in plan.tasks:
        counts[task.status] = counts.get(task.status, 0) + 1
    residual_ids, residual_hours = _residual(plan, result)
    origin = parse_datetime(plan.schedule_origin, "constraints.schedule_origin")
    finish = add_hours(origin, result.makespan)
    slack = None
    if plan.deadline:
        deadline = parse_datetime(plan.deadline, "constraints.deadline")
        slack = hours_between(finish, deadline)
    actual_hours = sum(
        (task.actuals.hours for task in plan.tasks if task.actuals.hours is not None),
        Decimal(0),
    )
    burn = None
    if plan.budget.hours > 0:
        burn = actual_hours / plan.budget.hours
    variance = _variance(plan)
    forecast = project(plan, result, roster)
    subplans = []
    for task in plan.tasks:
        if not task.subplan:
            continue
        timing = result.by_id.get(task.id)
        subplans.append(
            {
                "task_id": task.id,
                "path": task.subplan,
                "rolled_status": result.rolled_status.get(task.id, task.status),
                "rolled_hours": timing.expected if timing is not None else None,
            }
        )
    return {
        "plan_id": plan.plan_id,
        "directory": plan_directory_label(plan.directory, plan.plan_id),
        "version": plan.version,
        "progress_done": len(done),
        "progress_active": len(active),
        "progress_percent": fmt_percent(len(done), len(active)),
        "critical_path": list(result.critical_path),
        "critical_path_residual": residual_ids,
        "critical_residual_hours": residual_hours,
        "makespan_hours": result.makespan,
        "projected_finish": finish.isoformat(),
        "deadline": plan.deadline,
        "deadline_slack_hours": slack,
        "schedule_variance": variance,
        "budget_hours": plan.budget.hours,
        "actual_hours": actual_hours,
        "budget_burn": burn,
        "estimate_error": _estimate_error(plan, active),
        "blocked": _id_list(blocked),
        "awaiting_human": _id_list(waiting),
        "failed": _id_list(failed),
        "status_counts": counts,
        "priority": plan.priority,
        "forecast_hours": forecast.forecast_hours,
        "forecast_hour_ratio": forecast.hour_ratio,
        "forecast_warnings": list(forecast.warnings),
        "forecast_hold": forecast.hold,
        "forecast_tokens": forecast.forecast_tokens,
        "forecast_usd": forecast.forecast_usd,
        "subplans": subplans,
    }


def portfolio_document(entries: list[dict]) -> dict:
    return {
        "schema_version": 1,
        "kind": "portfolio",
        "schedule": "origin",
        "plans_count": len(entries),
        "tasks_done": sum(item["progress_done"] for item in entries),
        "tasks_active": sum(item["progress_active"] for item in entries),
        "blocked": sum(len(item["blocked"]) for item in entries),
        "awaiting_human": sum(len(item["awaiting_human"]) for item in entries),
        "failed": sum(len(item["failed"]) for item in entries),
        "plans": entries,
    }


def render_portfolio_yaml(entries: list[dict]) -> str:
    header = (
        "# Generated by `python -m planner portfolio`. Do not edit by hand.\n"
        "# Origin-based schedule. critical_residual_hours is unfinished critical effort.\n"
    )
    return header + dump_yaml(portfolio_document(entries))


def _names(ids: list[str]) -> str:
    return ", ".join(ids) if ids else "(none)"


def _variance_text(variance: dict) -> str:
    if variance["samples"] == 0:
        return "n/a"
    return (
        f"{fmt_hours(variance['actual_hours'])}h actual / "
        f"{fmt_hours(variance['expected_hours'])}h expected "
        f"(n={variance['samples']}, pooled ratio {fmt_ratio(variance['pooled_ratio'])})"
    )


def _error_text(error: dict | None) -> str:
    if error is None:
        return "n/a (plan is open, or it has no positive-duration done tasks)"
    text = (
        f"{fmt_ratio(error['pooled_ratio_vs_raw'])} "
        f"({fmt_hours(error['actual_hours'])}h actual / "
        f"{fmt_hours(error['raw_expected_hours'])}h raw expected)"
    )
    if "pooled_ratio_vs_calibrated" in error:
        text += f"; vs calibrated {fmt_ratio(error['pooled_ratio_vs_calibrated'])}"
    return text


def _counts_text(counts: dict) -> str:
    return ", ".join(f"{status}={counts.get(status, 0)}" for status in STATUSES)


def render_portfolio_md(entries: list[dict]) -> str:
    done = sum(item["progress_done"] for item in entries)
    active = sum(item["progress_active"] for item in entries)
    lines = [
        HEADER_MD.rstrip("\n"),
        "",
        f"- Live plans: {len(entries)}",
        f"- Tasks done: {done}/{active} ({fmt_percent(done, active)}%)",
        f"- Blocked: {sum(len(item['blocked']) for item in entries)}",
        f"- Awaiting human: {sum(len(item['awaiting_human']) for item in entries)}",
        f"- Failed: {sum(len(item['failed']) for item in entries)}",
        "",
    ]
    if not entries:
        lines.append("No live plans.")
        lines.append("")
        return "\n".join(lines)
    for item in entries:
        slack = item["deadline_slack_hours"]
        slack_text = "n/a" if slack is None else fmt_hours(slack)
        burn = item["budget_burn"]
        burn_text = "n/a" if burn is None else fmt_ratio(burn)
        deadline = item["deadline"] or "(none)"
        lines.extend(
            [
                f"## {item['plan_id']}",
                "",
                f"- Directory: {item['directory']}",
                f"- Version: {item['version']}",
                f"- Progress: {item['progress_done']}/{item['progress_active']} done "
                f"({item['progress_percent']}%)",
                f"- Critical path: {' -> '.join(item['critical_path']) or '(none)'}",
                "- Critical path residual: "
                f"{' -> '.join(item['critical_path_residual']) or '(none)'}",
                f"- Critical residual hours: {fmt_hours(item['critical_residual_hours'])}",
                f"- Makespan hours: {fmt_hours(item['makespan_hours'])}",
                f"- Projected finish: {item['projected_finish']}",
                f"- Deadline: {deadline}",
                f"- Deadline slack hours: {slack_text}",
                f"- Schedule variance: {_variance_text(item['schedule_variance'])}",
                f"- Budget hours: {fmt_hours(item['budget_hours'])}",
                f"- Actual hours: {fmt_hours(item['actual_hours'])}",
                f"- Budget burn: {burn_text}",
                f"- Estimate error: {_error_text(item['estimate_error'])}",
                f"- Priority: {item['priority']}",
                f"- Forecast hours: {fmt_hours(item['forecast_hours'])}",
                "- Forecast hour ratio: "
                + (
                    "n/a"
                    if item["forecast_hour_ratio"] is None
                    else fmt_ratio(item["forecast_hour_ratio"])
                ),
                "- Forecast warnings: " + (_names(item["forecast_warnings"])),
                f"- Forecast hold: {'yes' if item['forecast_hold'] else 'no'}",
                "- Forecast tokens: "
                + (
                    "n/a"
                    if item["forecast_tokens"] is None
                    else fmt_hours(item["forecast_tokens"])
                ),
                "- Forecast usd: "
                + ("n/a" if item["forecast_usd"] is None else fmt_hours(item["forecast_usd"])),
                "- Subplans: "
                + (
                    ", ".join(
                        f"{row['task_id']} -> {row['path']} ({row['rolled_status']})"
                        for row in item["subplans"]
                    )
                    or "(none)"
                ),
                f"- Blocked: {_names(item['blocked'])}",
                f"- Awaiting human: {_names(item['awaiting_human'])}",
                f"- Failed: {_names(item['failed'])}",
                f"- Status counts: {_counts_text(item['status_counts'])}",
                "",
            ]
        )
    return "\n".join(lines)
